// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPC0bqh9Q_FmR0ZOMcjs-3KfVPhpkFQVk',
    appId: '1:579924678976:web:ede42424942545296182a5',
    messagingSenderId: '579924678976',
    projectId: 'task-galaxy',
    authDomain: 'task-galaxy.firebaseapp.com',
    storageBucket: 'task-galaxy.appspot.com',
    measurementId: 'G-PN0T40N7J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxjxq6Q5JDKpNnLM84HIoNEx1UrXLJME',
    appId: '1:579924678976:android:1896dbe3aed0b3876182a5',
    messagingSenderId: '579924678976',
    projectId: 'task-galaxy',
    storageBucket: 'task-galaxy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0g5a4s4FoM2X49szVcq5TNrY-vNyXPBw',
    appId: '1:579924678976:ios:c0c7ba9379fe88506182a5',
    messagingSenderId: '579924678976',
    projectId: 'task-galaxy',
    storageBucket: 'task-galaxy.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0g5a4s4FoM2X49szVcq5TNrY-vNyXPBw',
    appId: '1:579924678976:ios:c0c7ba9379fe88506182a5',
    messagingSenderId: '579924678976',
    projectId: 'task-galaxy',
    storageBucket: 'task-galaxy.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPC0bqh9Q_FmR0ZOMcjs-3KfVPhpkFQVk',
    appId: '1:579924678976:web:1b2ea02989ce06b46182a5',
    messagingSenderId: '579924678976',
    projectId: 'task-galaxy',
    authDomain: 'task-galaxy.firebaseapp.com',
    storageBucket: 'task-galaxy.appspot.com',
    measurementId: 'G-KFXZX8CHS0',
  );
}
